=== Huluvu424242/lizenzkatalog/docs/annotation.dtd
<!-- $Id$ -->
<?thomas-michel document-status="draft" version="1.0"?>

<!ELEMENT annotation (text, notes?)+>

<!ELEMENT text (#PCDATA)>
<!ELEMENT notes (note)+>

<!ELEMENT note EMPTY>
<!ATTLIST note id ID #REQUIRED>
<!ATTLIST note type CDATA #REQUIRED>
<!ATTLIST note start CDATA #IMPLIED>
<!ATTLIST note end CDATA #IMPLIED>

=== Huluvu424242/lizenzkatalog/docs/test-gpl3.tei.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE annotation SYSTEM "annotation.dtd">
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<?thomas-schubert document-status="draft" version="2.0"?>
<annotation>
  <text xml:space="preserve">


   

GNU GENERAL PUBLIC LICENSE
Version 3, 29 June 2007

Copyright (C) 2007 Free Software Foundation, Inc.
&lt;https://fsf.org/&gt;
Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.

                            Preamble

The GNU General Public License is a free, copyleft license for
software and other kinds of works.


[[pol#distribution if=&quot;Distribution of modified versions&quot; then=&quot;allow&quot; because=&quot;Copyleft ensures user freedoms are preserved&quot;]]

To protect your rights, we need to prevent others from denying you
these rights or asking you to surrender the rights. Therefore, you
have certain responsibilities if you distribute copies of the software,
or if you modify it: responsibilities to respect the freedom of others.











  </text>
  <notes>
    <note id="a7" type="rul#nolia" start="59" end="246"/>
    <note id="a1" type="lic#name" value="GNU General Public License v3.0"/>
    <note id="a2" type="lic#spdx" value="GPL-3.0-only"/>
    <note id="a3" type="lic#fsf"/>
    <note id="a4" type="lic#osi"/>
    <note id="a5" type="rul#notice"/>
    <note id="a6" type="rul#lictxt"/>
    <note id="a8" type="use#app"/>
    <note id="a9" type="pol#distribution" value='if="Distribution of modified versions" then="allow" because="Copyleft ensures user freedoms are preserved"' if="Distribution of modified versions" then="allow" because="Copyleft ensures user freedoms are preserved" status="green" title="Copyleft ensures user freedoms are preserved" label="Distribution of modified versions"/>
    <note id="a10" type="pol#linking" value='if="Static linking with proprietary software" then="deny" because="GPLv3 requires derivative works to be GPL-compatible"' if="Static linking with proprietary software" then="deny" because="GPLv3 requires derivative works to be GPL-compatible" status="red" title="GPLv3 requires derivative works to be GPL-compatible" label="Static linking with proprietary software"/>
    <note id="a11" type="pol#tivoization" value='if="Use in locked-down hardware" then="deny" because="Tivoization clause forbids denial of user modification freedom"' if="Use in locked-down hardware" then="deny" because="Tivoization clause forbids denial of user modification freedom" status="red" title="Tivoization clause forbids denial of user modification freedom" label="Use in locked-down hardware"/>
    <note id="a12" type="pol#patent" value='if="Patent retaliation" then="allow" because="GPLv3 includes explicit patent-retaliation protection"' if="Patent retaliation" then="allow" because="GPLv3 includes explicit patent-retaliation protection" status="green" title="GPLv3 includes explicit patent-retaliation protection" label="Patent retaliation"/>
    <note id="a13" type="pol#network" value='if="Network use (SaaS)" then="conditional" because="AGPL required for network copyleft; GPLv3 itself is silent"' if="Network use (SaaS)" then="conditional" because="AGPL required for network copyleft; GPLv3 itself is silent" status="yellow" title="AGPL required for network copyleft; GPLv3 itself is silent" label="Network use (SaaS)"/>
    <note id="a14" type="pol#warranty" value='if="Warranty disclaimer" then="allow" because="GPLv3 permits distribution without warranty provided the disclaimer is kept intact"' if="Warranty disclaimer" then="allow" because="GPLv3 permits distribution without warranty provided the disclaimer is kept intact" status="green" title="GPLv3 permits distribution without warranty provided the disclaimer is kept intact" label="Warranty disclaimer"/>
    <note id="a15" type="pol#notice" value='if="License text inclusion" then="allow" because="GPLv3 requires full license text to be included with distribution"' if="License text inclusion" then="allow" because="GPLv3 requires full license text to be included with distribution" status="green" title="GPLv3 requires full license text to be included with distribution" label="License text inclusion"/>
    <note id="a16" type="pol#source" value='if="Providing source code" then="allow" because="GPLv3 mandates corresponding source for distributed binaries"' if="Providing source code" then="allow" because="GPLv3 mandates corresponding source for distributed binaries" status="green" title="GPLv3 mandates corresponding source for distributed binaries" label="Providing source code"/>
    <note id="a17" type="pol#_section" present="true"/>
  </notes>
</annotation>

=== Huluvu424242/lizenzkatalog/docs/apache-2.0.tei.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE annotation SYSTEM "annotation.dtd">
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<?thomas-schubert document-status="draft" version="1.0"?>
<annotation>
  <text>
    Apache License, Version 2.0


Apache License, Version 2.0

Permission is hereby granted, free of charge, to any person obtaining a copy of this software
and associated documentation files (the &quot;Software&quot;), to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

You must include a NOTICE file when provided by the work.
This license includes an express patent grant.
Trade names, trademarks, service marks are not licensed.

THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND...

Note: Patent grant overlaps with rights granted above.



  </text>
  <notes>
    <note id="lic" type="license" start="29" end="822" type="apache-2.0" url="https://www.apache.org/licenses/LICENSE-2.0"/>
    <note id="t1" type="title" start="30" end="44"/>
    <note id="v1" type="version" start="54" end="57"/>
    <note id="gr1" type="grant" start="59" end="69"/>
    <note id="r1" type="rights" start="209" end="286"/>
    <note id="c1" type="condition" start="536" end="593" type="notice"/>
    <note id="c2" type="condition" start="594" end="640" type="patent"/>
    <note id="p1" type="patent" start="627" end="639"/>
    <note id="c3" type="condition" start="641" end="697" type="trademark"/>
    <note id="d1" type="disclaimer" start="699" end="764"/>
    <note id="rel1" type="relation" start="766" end="785"/>
    <note id="xr1" type="xref" start="785" end="819" ref="#p1"/>
  </notes>
</annotation>
